version: '3'

services:

  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    #restart: always
    depends_on:
      - front
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/revers-proxy.conf:/etc/nginx/conf.d/default.conf"
      - "/home/sysadmin/ssl:/home/sysadmin/ssl/:rw"

  back:
    image: openjdk:17-jdk-alpine
    working_dir: /app
    command: sh -c "java -jar *.jar"
    ports:
      - "8080:8080"
    depends_on:
      - "dbserver"
    restart: on-failure
    volumes:
      - ./backend/target:/app

  dbserver:
    image: mysql:8.0.33
    volumes:
      - /home/sysadmin/announce-project2/database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=jip@345_jip
      - MYSQL_USER=jip
      - MYSQL_PASSWORD=jip@345_jip
      - TZ=UTC
      - LANG=en_US.UTF-8
      - MYSQL_DATABASE=mydb

  front:
    image: front-img
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
